<?php

/**
 * @file
 * Contains modulo_prueba.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function modulo_prueba_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the modulo_prueba module.
    case 'help.page.modulo_prueba':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('modulo para obtener datos de un JSON') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function modulo_prueba_theme() {
  return [
    'modulo_prueba' => [
      'render element' => 'children',
    ],
  ];
}
